feature_generator: D1
normalizer: max # max mean
eigenvec_func: eigh # eigh
sort_ev: True # False
number_of_bins: 10
ratio_of_train_data: 70
data_output_folder: output

hydra:
  output_subdir: null
  run:
    dir: .
